
services:

    # auto-register all controllers as services
    AdvancedObjectSearchBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    bundle.advanced_object_search.es_client:
        class: Elasticsearch\Client
        factory: ['AdvancedObjectSearchBundle\Tools\EsClientFactory', getESClient]

    bundle.advanced_object_search.service:
        class: AdvancedObjectSearchBundle\Service
        arguments:
            - '@logger'
            - '@pimcore_admin.security.token_storage_user_resolver'
            - '@bundle.advanced_object_search.es_client'
            - '@bundle.advanced_object_search.filter_locator'

        tags:
            - { name: monolog.logger, channel: pimcore_advanced_object_search }

    bundle.advanced_object_search.eventlisteners:
        class: AdvancedObjectSearchBundle\EventListener\IndexUpdateListener
        arguments:
            - '@bundle.advanced_object_search.service'
        tags:
            - { name: kernel.event_listener, event: pimcore.dataobject.postUpdate, method: updateObject }
            - { name: kernel.event_listener, event: pimcore.dataobject.postAdd, method: updateObject }
            - { name: kernel.event_listener, event: pimcore.dataobject.preDelete, method: deleteObject }
            - { name: kernel.event_listener, event: pimcore.class.postUpdate, method: updateMapping }
            - { name: kernel.event_listener, event: pimcore.class.postDelete, method: deleteIndex }
            - { name: kernel.event_listener, event: pimcore.system.maintenance, method: registerMaintenanceJob }

    bundle.advanced_object_search.filter_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        tags: ['container.service_locator']

    bundle.advanced_object_search.filter.default:
        class: AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\DefaultAdapter
        shared: false
        arguments:
            - '@bundle.advanced_object_search.service'

    bundle.advanced_object_search.filter.calculatedValue:
        class: AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\CalculatedValue
        shared: false
        arguments:
            - '@bundle.advanced_object_search.service'

    bundle.advanced_object_search.filter.checkbox:
        class: AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\Checkbox
        shared: false
        arguments:
            - '@bundle.advanced_object_search.service'

    bundle.advanced_object_search.filter.country:
        class: AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\Country
        shared: false
        arguments:
            - '@bundle.advanced_object_search.service'

    bundle.advanced_object_search.filter.countrymultiselect:
        class: AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\Countrymultiselect
        shared: false
        arguments:
            - '@bundle.advanced_object_search.service'

    bundle.advanced_object_search.filter.date:
        class: AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\Date
        shared: false
        arguments:
            - '@bundle.advanced_object_search.service'

    bundle.advanced_object_search.filter.datetime:
        class: AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\Datetime
        shared: false
        arguments:
            - '@bundle.advanced_object_search.service'

    bundle.advanced_object_search.filter.fieldcollections:
        class: AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\Fieldcollections
        shared: false
        arguments:
            - '@bundle.advanced_object_search.service'

    AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\ManyToOneRelation:
        class: AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\ManyToOneRelation
        shared: false
        arguments:
            - '@bundle.advanced_object_search.service'

    bundle.advanced_object_search.filter.language:
        class: AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\Language
        shared: false
        arguments:
            - '@bundle.advanced_object_search.service'

    bundle.advanced_object_search.filter.languagemultiselect:
        class: AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\Languagemultiselect
        shared: false
        arguments:
            - '@bundle.advanced_object_search.service'

    bundle.advanced_object_search.filter.localizedfields:
        class: AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\Localizedfields
        shared: false
        arguments:
            - '@bundle.advanced_object_search.service'
            - '@pimcore.locale'

    AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\ManyToManyRelation:
        class: AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\ManyToManyRelation
        shared: false
        arguments:
            - '@bundle.advanced_object_search.service'

    AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\AdvancedManyToManyRelation:
        class: AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\AdvancedManyToManyRelation
        shared: false
        arguments:
            - '@bundle.advanced_object_search.service'

    bundle.advanced_object_search.filter.multiselect:
        class: AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\Multiselect
        shared: false
        arguments:
            - '@bundle.advanced_object_search.service'

    bundle.advanced_object_search.filter.numeric:
        class: AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\Numeric
        shared: false
        arguments:
            - '@bundle.advanced_object_search.service'

    bundle.advanced_object_search.filter.objectbricks:
        class: AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\Objectbricks
        shared: false
        arguments:
            - '@bundle.advanced_object_search.service'

    AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\ManyToManyObjectRelation:
        class: AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\ManyToManyObjectRelation
        shared: false
        arguments:
            - '@bundle.advanced_object_search.service'

    AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\AdvancedManyToManyObjectRelation:
        class: AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\AdvancedManyToManyObjectRelation
        shared: false
        arguments:
            - '@bundle.advanced_object_search.service'

    bundle.advanced_object_search.filter.quantityValue:
        class: AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\QuantityValue
        shared: false
        arguments:
            - '@bundle.advanced_object_search.service'

    bundle.advanced_object_search.filter.select:
        class: AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\Select
        shared: false
        arguments:
            - '@bundle.advanced_object_search.service'

    bundle.advanced_object_search.filter.time:
        class: AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\Time
        shared: false
        arguments:
            - '@bundle.advanced_object_search.service'

    bundle.advanced_object_search.filter.user:
        class: AdvancedObjectSearchBundle\Filter\FieldDefinitionAdapter\User
        shared: false
        arguments:
            - '@bundle.advanced_object_search.service'













